
TOK_DCL( tkDot      , No, "."   )
TOK_DCL( tkComma    , Cma, ","   )
TOK_DCL( tkDArrow   , Asg, "=>"  )
TOK_DCL( tkAsg      , Asg, "="   )
TOK_DCL( tkAsgAdd   , Asg, "+="  )
TOK_DCL( tkAsgSub   , Asg, "-="  )
TOK_DCL( tkAsgMul   , Asg, "*="  )
TOK_DCL( tkAsgDiv   , Asg, "/="  )
TOK_DCL( tkAsgMod   , Asg, "%="  )
TOK_DCL( tkAsgAnd   , Asg, "&="  )
TOK_DCL( tkAsgXor   , Asg, "^="  )
TOK_DCL( tkAsgOr    , Asg, "|="  )
TOK_DCL( tkAsgLsh   , Asg, "<<=" )
TOK_DCL( tkAsgRsh   , Asg, ">>=" )
TOK_DCL( tkAsgRs2   , Asg, ">>>=")
TOK_DCL( tkQMark    , Que, "?"   )
TOK_DCL( tkColon    , No , ":"   )
TOK_DCL( tkLogOr    , Lor, "||"  )
TOK_DCL( tkLogAnd   , Lan, "&&"  )
TOK_DCL( tkOr       , Bor, "|"   )
TOK_DCL( tkXor      , Xor, "^"   )
TOK_DCL( tkAnd      , Ban, "&"   )
TOK_DCL( tkEQ       , Equ, "=="  )
TOK_DCL( tkNE       , Equ, "!="  )
TOK_DCL( tkEqv      , Equ, "===" )
TOK_DCL( tkNEqv     , Equ, "!==" )
TOK_DCL( tkLT       , Cmp, "<"   )
TOK_DCL( tkLE       , Cmp, "<="  )
TOK_DCL( tkGT       , Cmp, ">"   )
TOK_DCL( tkGE       , Cmp, ">="  )
TOK_DCL( tkLsh      , Shf, "<<"  )
TOK_DCL( tkRsh      , Shf, ">>"  )
TOK_DCL( tkRs2      , Shf, ">>>" )
TOK_DCL( tkAdd      , Add, "+"   )
TOK_DCL( tkSub      , Add, "-"   )
TOK_DCL( tkStar     , Mul, "*"   )
TOK_DCL( tkDiv      , Mul, "/"   )
TOK_DCL( tkPct      , Mul, "%"   )
TOK_DCL( tkTilde    , No , "~"   )
TOK_DCL( tkBang     , No , "!"   )
TOK_DCL( tkInc      , No , "++"  )
TOK_DCL( tkDec      , No , "--"  )
TOK_DCL( tkRParen   , No , ")"   )
TOK_DCL( tkDotDotDot, No , "..." )
TOK_DCL( tkLParen   , No , "("   )
TOK_DCL( tkLBrack   , No , "["   )
